# .github/config.yml
blank_issues_enabled: false # ç¦æ­¢åˆ›å»ºç©ºç™½ Issue
contact_links:
  - name: ğŸ’¬ æ™®éè®¨è®º (General Discussion)
    url: https://github.com/Karlbaey/Haku/discussions/new/choose
    about: å¦‚æœä½ åªæ˜¯æƒ³æé—®æˆ–è¿›è¡Œå¼€æ”¾å¼è®¨è®ºï¼Œè¯·ä½¿ç”¨ Discussionsã€‚
